2020-08-06 04:54:45,953 — api.controller — ERROR —predict:81 — Exception on Flask server (predict function): make_prediction() got an unexpected keyword argument 'output_path' 
                 traceback: Traceback (most recent call last):
  File "/home/aikauel/enap/aerialnet_project/packages/ml_api/api/controller.py", line 73, in predict
    response_data = make_prediction(image_bytes.content, imgURL=img_url, generateOutputImg=generateOutputImg, output_path=outputImgPath)
TypeError: make_prediction() got an unexpected keyword argument 'output_path'
Traceback (most recent call last):
  File "/home/aikauel/enap/aerialnet_project/packages/ml_api/api/controller.py", line 73, in predict
    response_data = make_prediction(image_bytes.content, imgURL=img_url, generateOutputImg=generateOutputImg, output_path=outputImgPath)
TypeError: make_prediction() got an unexpected keyword argument 'output_path'
2020-08-06 09:52:30,372 — api.controller — ERROR —predict:81 — Exception on Flask server (predict function): <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1596707550.370924430","description":"Error received from peer ipv4:127.0.0.1:8500","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"Deadline Exceeded","grpc_status":4}"
> 
                 traceback: Traceback (most recent call last):
  File "/home/enap_vm/aerialnet/packages/ml_api/api/controller.py", line 73, in predict
    response_data = make_prediction(image_bytes.content, imgURL=img_url, generateOutputImg=generateOutputImg, outputPath=outputImgPath)
  File "/data/anaconda/envs/aerialnet_env/lib/python3.6/site-packages/aerialnet-0.1.3-py3.6.egg/aerialnet/predict.py", line 54, in make_prediction
    result = grpcStub.Predict(request, 20.0)  # 10 secs timeout
  File "/data/anaconda/envs/aerialnet_env/lib/python3.6/site-packages/grpcio-1.30.0-py3.6-linux-x86_64.egg/grpc/_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/data/anaconda/envs/aerialnet_env/lib/python3.6/site-packages/grpcio-1.30.0-py3.6-linux-x86_64.egg/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1596707550.370924430","description":"Error received from peer ipv4:127.0.0.1:8500","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
Traceback (most recent call last):
  File "/home/enap_vm/aerialnet/packages/ml_api/api/controller.py", line 73, in predict
    response_data = make_prediction(image_bytes.content, imgURL=img_url, generateOutputImg=generateOutputImg, outputPath=outputImgPath)
  File "/data/anaconda/envs/aerialnet_env/lib/python3.6/site-packages/aerialnet-0.1.3-py3.6.egg/aerialnet/predict.py", line 54, in make_prediction
    result = grpcStub.Predict(request, 20.0)  # 10 secs timeout
  File "/data/anaconda/envs/aerialnet_env/lib/python3.6/site-packages/grpcio-1.30.0-py3.6-linux-x86_64.egg/grpc/_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/data/anaconda/envs/aerialnet_env/lib/python3.6/site-packages/grpcio-1.30.0-py3.6-linux-x86_64.egg/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.DEADLINE_EXCEEDED
	details = "Deadline Exceeded"
	debug_error_string = "{"created":"@1596707550.370924430","description":"Error received from peer ipv4:127.0.0.1:8500","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"Deadline Exceeded","grpc_status":4}"
>
